# Generated by Django 4.1 on 2022-08-16 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imGE", models.ImageField(upload_to=True)),
                ("name", models.CharField(max_length=100)),
                ("userid", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")], max_length=50
                    ),
                ),
                ("roll_no", models.CharField(max_length=20)),
                (
                    "year",
                    models.CharField(
                        choices=[
                            ("Y22", "Y22"),
                            ("Y21", "Y21"),
                            ("Y20", "Y20"),
                            ("Y19", "Y19"),
                            ("Y18", "Y18"),
                            ("Y17", "Y17"),
                            ("Y16", "Y16"),
                            ("Y15", "Y15"),
                            ("Y14", "Y14"),
                            ("Y13", "Y13"),
                            ("Y12", "Y12"),
                            ("Y11", "Y11"),
                            ("Y10", "Y10"),
                            ("Y9", "Y9"),
                            ("Y8", "Y8"),
                            ("Other", "Other"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "branch",
                    models.CharField(
                        choices=[
                            ("Aerospace Engineering", "Aerospace Engineering"),
                            (
                                "Biological Sciences and Bioengineering",
                                "Biological Sciences and Bioengineering",
                            ),
                            ("Civil Engineering", "Civil Engineering"),
                            ("Chemical Engineering", "Chemical Engineering"),
                            ("Chemistry", "Chemistry"),
                            (
                                "Computer Science and Engineering",
                                "Computer Science and Engineering",
                            ),
                            ("Cognitive Sciences", "Cognitive Sciences"),
                            ("Dean Of Academic Affairs", "Dean Of Academic Affairs"),
                            ("Dean Of Resource Affairs", "Dean Of Resource Affairs"),
                            (
                                "Dean Of Research and Development",
                                "Dean Of Research and Development",
                            ),
                            ("Economic Sciences", "Economic Sciences"),
                            ("Electrical Engineering", "Electrical Engineering"),
                            ("EEM", "EEM"),
                            ("Earth Sciences", "Earth Sciences"),
                            (
                                "Humanities and Social Sciences",
                                "Humanities and Social Sciences",
                            ),
                            (
                                "Industrial and Management Engineering",
                                "Industrial and Management Engineering",
                            ),
                            ("Laser Technology", "Laser Technology"),
                            ("MDes", "MDes"),
                            ("Mechanical Engineering", "Mechanical Engineering"),
                            (
                                "Material Science and Engineering",
                                "Material Science and Engineering",
                            ),
                            (
                                "Mathematics and Statistics",
                                "Mathematics and Statistics",
                            ),
                            ("Mat. and Met.Engg.", "Mat. and Met.Engg."),
                            (
                                "Materials Science Programme",
                                "Materials Science Programme",
                            ),
                            (
                                "Mathematics And Scientific Comp",
                                "Mathematics And Scientific Comp",
                            ),
                            ("Nuc. Engg. and Tech Prog.", "Nuc. Engg. and Tech Prog."),
                            ("Null", "Null"),
                            ("Physics", "Physics"),
                            (
                                "Photonics Science and Engg.",
                                "Photonics Science and Engg.",
                            ),
                            ("Statistics", "Statistics"),
                            (
                                "Statistics And Data Science",
                                "Statistics And Data Science",
                            ),
                            (
                                "Sustainable Energy Engineering",
                                "Sustainable Energy Engineering",
                            ),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "programme",
                    models.CharField(
                        choices=[
                            ("BS", "BS"),
                            ("BS-MBA", "BS-MBA"),
                            ("BS-MS", "BS-MS"),
                            ("BS-MT", "BS-MT"),
                            ("BT-M.Des", "BT-M.Des"),
                            ("BT-MBA", "BT-MBA"),
                            ("BT-MS", "BT-MS"),
                            ("B.Tech", "B.Tech"),
                            ("DIIT", "DIIT"),
                            ("Exchange Programme", "Exchange Programme"),
                            ("MBA", "MBA"),
                            ("M.Des", "M.Des"),
                            ("MS-Research", "MS-Research"),
                            ("MSc(2 yr)", "MSc(2 yr)"),
                            ("MSc(Int)", "MSc(Int)"),
                            ("MSc-PhD(Dual)", "MSc-PhD(Dual)"),
                            ("MT(Dual)", "MT(Dual)"),
                            ("M.Tech", "M.Tech"),
                            ("PGPEX-VLM", "PGPEX-VLM"),
                            ("PhD", "PhD"),
                            ("Prep.", "Prep."),
                            ("SURGE", "SURGE"),
                            ("eMasters", "eMasters"),
                        ],
                        max_length=30,
                    ),
                ),
                ("room_no", models.CharField(max_length=30)),
                (
                    "hall",
                    models.CharField(
                        choices=[
                            ("HALL 2", "HALL 2"),
                            ("HALL 13", "HALL 13"),
                            ("HALL 1", "HALL 1"),
                            ("HALL 3", "HALL 3"),
                            ("HALL 4", "HALL 4"),
                            ("HALL 5", "HALL 5"),
                            ("HALL 6", "HALL 6"),
                            ("HALL 7", "HALL 7"),
                            ("HALL 8", "HALL 8"),
                            ("HALL 9", "HALL 9"),
                            ("HALL 10", "HALL 10"),
                            ("HLL 11", "HLL 11"),
                            ("HALL 12", "HALL 12"),
                            ("GH", "GH"),
                            ("DAY", "DAY"),
                            ("CPWD", "CPWD"),
                            ("ACES", "ACES"),
                            ("NRA", "NRA"),
                            ("RA", "RA"),
                            ("SBRA", "SBRA"),
                            ("TYPE 1", "TYPE 1"),
                            ("TYPE 1B", "TYPE 1B"),
                            ("UNKN", "UNKN"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "blood_group",
                    models.CharField(
                        choices=[
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        max_length=5,
                    ),
                ),
                ("hometown", models.CharField(default="Kanpur", max_length=100)),
                ("state", models.CharField(default="U.P.", max_length=100)),
                ("country", models.CharField(default="India", max_length=100)),
                (
                    "student_guide",
                    models.ForeignKey(
                        default=210153,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student.student",
                    ),
                ),
            ],
            options={"db_table": "student",},
        ),
    ]
