# Generated by Django 4.1 on 2022-08-16 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0002_alter_student_student_guide"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="student_guide",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="student.student",
            ),
        ),
    ]
