# Generated by Django 4.1 on 2022-08-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0003_alter_student_student_guide"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="imGE",
            field=models.ImageField(blank=True, null=True, upload_to=True),
        ),
    ]
